### ISSUE TITLE
acquire: all players get kicked

### ISSUE THREAD

**Issue by bennn** [bennn/gtp-benchmarks#32]
Looks like the ordered strategy & random strategy in acquire both produce players that break the rules.

Find or make a strategy for acquire that can finish a game.

**Comment by bennn** [comment]
cc @llazarek
sounds like we need to fix this asap

**Comment by LLazarek** [comment]
Ah so you already knew about this!
I've been tinkering with possible fixes but it seems like there are several bugs that have been lurking because most of the game's functionality has never been exercised.

Two examples I've noticed:
- There seem to be player actions that the game doesn't implement handling for (assuming that whatever `SINGLETON` is supposed to mean really is a valid action, though a brief search of the game rules doesn't bring up anything with that name)
- helpers used by the game engine can never be called because they can only produce a type assertion error (like `shares-available?`).

Matthias's original seems to differ in the admin's handling of `SINGLETON` actions and the implementation of those helpers, so I guess these are bugs that came about in the trimming down to benchmark-ness.
